# Generated by Django 4.2.5 on 2023-09-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('description', models.TextField()),
                ('version', models.TextField()),
                ('releasedate', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
