# Generated by Django 4.2.5 on 2023-10-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='releasedate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
