# Generated by Django 4.2.5 on 2023-11-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rarity',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
